# Encoding Categorical Data
# Sanjay Gupta
# Date: 23-August-2021

# Most of the Machine Learning Algorithms accepts only Numerical data as input. For example K-Nearest neighbor Algorithm calculates the Euclidean distance between the two observations, of a feature. To calculate the Euclidean distance between the two observations the input that is passed should be of Numerical type. So the Categorical data must be transformed or encoded into Numerical type before feeding data to an Algorithm, which in turn yields better results.

# Step # 1: Importing Libraries

In [1]:
import pandas as pd
import numpy as np

# Step # 2: Load the Data into Python

In [2]:
#specify URL where data is located
url = 'https://raw.githubusercontent.com/sanjaygupta1963/Pythoncoding/main/price_train_r_exam_sem2.csv'

# Load Dataset from the Github URL
# pd.read_csv() function: Read a comma-separated values (csv) file into DataFrame.
dframe = pd.read_csv(url)
dframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3466 entries, 0 to 3465
Data columns (total 25 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   X1                            3466 non-null   int64
 1   id                            3466 non-null   int64
 2   host_is_superhost             3466 non-null   bool
 3   host_response_rate            3466 non-null   object
 4   host_response_time            3466 non-null   object
 5   host_listings_count           3466 non-null   int64
 6   host_identity_verified        3466 non-null   bool
 7   accommodates                  3466 non-null   int64
 8   neighbourhood_group_cleansed  3466 non-null   object
 9   property_type                 3466 non-null   object
 10  room_type                     3466 non-null   object
 11  latitude                      3466 non-null   float64
 12  longitude                     3466 non-null   float64
 13  guests_included               3466 non-null   int64
 14  bathrooms                     3466 non-null   float64
 15  bedrooms                      3466 non-null   int64
 16  beds                          3466 non-null   int64
 17  bed_type                      3466 non-null   object
 18  amenities                     3466 non-null   object
 19  cleaning_fee                  3466 non-null   object
 20  minimum_nights                3466 non-null   int64
 21  maximum_nights                3466 non-null   int64
 22  instant_bookable              3466 non-null   bool
 23  cancellation_policy           3466 non-null   object
 24  price                         3466 non-null   object
dtypes: bool(3), float64(3), int64(9), object(10)
memory usage: 606.0+ KB

In [3]:
# Step # 3: Select Only Object Datatypes Columns
# Describing all columns of a DataFrame regardless of data type.
# dframe.describe(include='all') 
# Describing a only Numeric columns from a DataFrame by accessing it as an attribute.
# dframe.describe(include=[np.number])

# Select Object Datatypes Columns for our scope here
#obj_df=dframe.describe(include='object') 
#obj_df.head(10)

# Step # 3: Cleaning the Data

In [4]:
# Convert the Entire Dataframe Columns into the Object (String) Datatype
# This is pre-requiste to run the String Repalcement Command in the next Row
# obj_df = obj_df.applymap(str)
# obj_df.info()

In [5]:
# Removing All the possible Special Characters from the Entire Dataframe through a FOR Loop
special_char=[';','%','$','!','&','{','}','"','/']
n=0
for i in special_char:
    dframe = dframe.replace(special_char[n],'',regex=True)
    # print(special_char[n])
    n += 1
# For Loop Ends

# Display the first 10 rows of the dataset
dframe.head(10)

,X1,id,host_is_superhost,host_response_rate,host_response_time,host_listings_count,host_identity_verified,accommodates,neighbourhood_group_cleansed,property_type,...,bedrooms,beds,bed_type,amenities,cleaning_fee,minimum_nights,maximum_nights,instant_bookable,cancellation_policy,price
0,5460,22146017,False,99,within an hour,521,False,5,Downtown,Apartment,...,2,2,Real Bed,"TV,Internet,Wifi,Kitchen,Elevator,Heating,Fami...",$129.00,2,1125,True,strict,$279.00
1,4143,18638163,True,100,within an hour,1,True,2,Queen Anne,House,...,0,1,Real Bed,"TV,Cable TV,Internet,Wifi,Air conditioning,Kit...",$50.00,2,30,True,moderate,$99.00
2,5802,22734110,True,100,within an hour,1,False,4,Rainier Valley,Guest suite,...,1,2,Real Bed,"TV,Wifi,Air conditioning,Kitchen,Free street p...",$25.00,2,28,False,moderate,$75.00
3,776,3946674,True,90,within a few hours,1,True,2,Central Area,House,...,1,1,Real Bed,"Internet,Wifi,Kitchen,Pets live on this proper...",$0.00,2,30,False,flexible,$70.00
4,6064,23610186,True,100,within an hour,4,True,8,Beacon Hill,House,...,3,3,Real Bed,"TV,Wifi,Kitchen,Free parking on premises,Smoki...",$99.00,2,12,False,flexible,$242.00
5,2757,13533608,False,100,within a few hours,4,True,8,Magnolia,Townhouse,...,3,3,Real Bed,"TV,Wifi,Kitchen,Indoor fireplace,Heating,Famil...",$100.00,2,1125,False,strict_14_with_grace_period,$430.00
6,7786,29396738,True,100,within an hour,1,False,3,Other neighborhoods,Bungalow,...,1,2,Real Bed,"TV,Wifi,Free street parking,Heating,Washer,Dry...",$20.00,1,8,False,moderate,$60.00
7,7012,26667492,False,100,within an hour,9,False,4,Downtown,Condominium,...,1,2,Real Bed,"TV,Cable TV,Wifi,Air conditioning,Kitchen,Elev...",$50.00,3,1125,True,strict_14_with_grace_period,$125.00
8,6019,23417458,True,100,within an hour,2,False,2,Downtown,Apartment,...,1,1,Real Bed,"TV,Wifi,Air conditioning,Pool,Kitchen,Pets all...",$110.00,1,1125,True,strict_14_with_grace_period,$225.00
9,3766,17465443,False,99,within an hour,152,False,2,Downtown,Loft,...,1,1,Real Bed,"TV,Internet,Wifi,Kitchen,Gym,Elevator,Buzzerwi...",$89.00,2,1125,False,strict_14_with_grace_period,$219.00

In [6]:
# Note that Comma ',' should not be repalced from the Amenities Columns , so it has to be replaced through a separate Command.
# Note that Dollar Symbol '$' is not getting replaced by the above For Loop Command, 
# therefore so it has to be replaced through a separate Command.
# Removing the $ sign from the cleaning_fee and price Columns 
dframe['price'] = dframe['price'].str.replace('$','',regex=True)
dframe['price'] = dframe['price'].str.replace(',','',regex=True)
dframe['cleaning_fee'] = dframe['cleaning_fee'].str.replace('$','',regex=True)
dframe['cleaning_fee'] = dframe['cleaning_fee'].str.replace(',','',regex=True)
dframe.head(10)

,X1,id,host_is_superhost,host_response_rate,host_response_time,host_listings_count,host_identity_verified,accommodates,neighbourhood_group_cleansed,property_type,...,bedrooms,beds,bed_type,amenities,cleaning_fee,minimum_nights,maximum_nights,instant_bookable,cancellation_policy,price
0,5460,22146017,False,99,within an hour,521,False,5,Downtown,Apartment,...,2,2,Real Bed,"TV,Internet,Wifi,Kitchen,Elevator,Heating,Fami...",129.00,2,1125,True,strict,279.00
1,4143,18638163,True,100,within an hour,1,True,2,Queen Anne,House,...,0,1,Real Bed,"TV,Cable TV,Internet,Wifi,Air conditioning,Kit...",50.00,2,30,True,moderate,99.00
2,5802,22734110,True,100,within an hour,1,False,4,Rainier Valley,Guest suite,...,1,2,Real Bed,"TV,Wifi,Air conditioning,Kitchen,Free street p...",25.00,2,28,False,moderate,75.00
3,776,3946674,True,90,within a few hours,1,True,2,Central Area,House,...,1,1,Real Bed,"Internet,Wifi,Kitchen,Pets live on this proper...",0.00,2,30,False,flexible,70.00
4,6064,23610186,True,100,within an hour,4,True,8,Beacon Hill,House,...,3,3,Real Bed,"TV,Wifi,Kitchen,Free parking on premises,Smoki...",99.00,2,12,False,flexible,242.00
5,2757,13533608,False,100,within a few hours,4,True,8,Magnolia,Townhouse,...,3,3,Real Bed,"TV,Wifi,Kitchen,Indoor fireplace,Heating,Famil...",100.00,2,1125,False,strict_14_with_grace_period,430.00
6,7786,29396738,True,100,within an hour,1,False,3,Other neighborhoods,Bungalow,...,1,2,Real Bed,"TV,Wifi,Free street parking,Heating,Washer,Dry...",20.00,1,8,False,moderate,60.00
7,7012,26667492,False,100,within an hour,9,False,4,Downtown,Condominium,...,1,2,Real Bed,"TV,Cable TV,Wifi,Air conditioning,Kitchen,Elev...",50.00,3,1125,True,strict_14_with_grace_period,125.00
8,6019,23417458,True,100,within an hour,2,False,2,Downtown,Apartment,...,1,1,Real Bed,"TV,Wifi,Air conditioning,Pool,Kitchen,Pets all...",110.00,1,1125,True,strict_14_with_grace_period,225.00
9,3766,17465443,False,99,within an hour,152,False,2,Downtown,Loft,...,1,1,Real Bed,"TV,Internet,Wifi,Kitchen,Gym,Elevator,Buzzerwi...",89.00,2,1125,False,strict_14_with_grace_period,219.00

# Method # 1 Using Get Dummies for converting Categorical Labels into Dummy Variables

# Creating Dummy variables is the way of including categorical variables into the regression modeling.
# A dummy variable is a variable that takes values of 0 and 1.
# Depending on the Multiple Value of a Column, Dummy Variable process creates multiple Variables having the values 1 and 0 indicating present and absence of the same.

In [7]:
# Create Dummy Variables for property_type variable with Prefix parameter
# ptype = pd.get_dummies(obj_df['property_type'],prefix="pt")

# In the below code snippet, we passed an argument drop_first=True, 
# this indicates it drops one Dummy Variable from all the dummy variables created for a feature. 
# It is to be dropped because it causes Dummy variable Trap, 
# which is called as some of the features are highly correlated which results in predicting of another feature. 
# So to avoid this situation, we are dropping one dummy variable created after encoding.

# hrtime = pd.get_dummies(dframe['host_response_time'],drop_first=True)


# Create Dummy Variables for host_response_time variable without Prefix parameter
hrtime = pd.get_dummies(dframe['host_response_time'])
# Create Dummy Variables forneighbourhood_group_cleansed variable without Prefix parameter
ngclean = pd.get_dummies(dframe['neighbourhood_group_cleansed'])
# Create Dummy Variables for property_type variable without Prefix parameter
ptype = pd.get_dummies(dframe['property_type'])
# Create Dummy Variables for bed_type variable
bed = pd.get_dummies(dframe['bed_type'])
# Create Dummy Variables for cancellation_policy variable
cpolicy = pd.get_dummies(dframe['cancellation_policy'])

# Concatenate All the Dummy Variables inot the Dataframe
dum_df = pd.concat([dframe,hrtime,ngclean,ptype,bed,cpolicy], axis=1)
dum_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3466 entries, 0 to 3465
Data columns (total 82 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   X1                            3466 non-null   int64
 1   id                            3466 non-null   int64
 2   host_is_superhost             3466 non-null   bool
 3   host_response_rate            3466 non-null   object
 4   host_response_time            3466 non-null   object
 5   host_listings_count           3466 non-null   int64
 6   host_identity_verified        3466 non-null   bool
 7   accommodates                  3466 non-null   int64
 8   neighbourhood_group_cleansed  3466 non-null   object
 9   property_type                 3466 non-null   object
 10  room_type                     3466 non-null   object
 11  latitude                      3466 non-null   float64
 12  longitude                     3466 non-null   float64
 13  guests_included               3466 non-null   int64
 14  bathrooms                     3466 non-null   float64
 15  bedrooms                      3466 non-null   int64
 16  beds                          3466 non-null   int64
 17  bed_type                      3466 non-null   object
 18  amenities                     3466 non-null   object
 19  cleaning_fee                  3466 non-null   object
 20  minimum_nights                3466 non-null   int64
 21  maximum_nights                3466 non-null   int64
 22  instant_bookable              3466 non-null   bool
 23  cancellation_policy           3466 non-null   object
 24  price                         3466 non-null   object
 25  a few days or more            3466 non-null   uint8
 26  within a day                  3466 non-null   uint8
 27  within a few hours            3466 non-null   uint8
 28  within an hour                3466 non-null   uint8
 29  Ballard                       3466 non-null   uint8
 30  Beacon Hill                   3466 non-null   uint8
 31  Capitol Hill                  3466 non-null   uint8
 32  Cascade                       3466 non-null   uint8
 33  Central Area                  3466 non-null   uint8
 34  Delridge                      3466 non-null   uint8
 35  Downtown                      3466 non-null   uint8
 36  Interbay                      3466 non-null   uint8
 37  Lake City                     3466 non-null   uint8
 38  Magnolia                      3466 non-null   uint8
 39  Northgate                     3466 non-null   uint8
 40  Other neighborhoods           3466 non-null   uint8
 41  Queen Anne                    3466 non-null   uint8
 42  Rainier Valley                3466 non-null   uint8
 43  Seward Park                   3466 non-null   uint8
 44  University District           3466 non-null   uint8
 45  West Seattle                  3466 non-null   uint8
 46  Aparthotel                    3466 non-null   uint8
 47  Apartment                     3466 non-null   uint8
 48  Bed and breakfast             3466 non-null   uint8
 49  Boat                          3466 non-null   uint8
 50  Boutique hotel                3466 non-null   uint8
 51  Bungalow                      3466 non-null   uint8
 52  Cabin                         3466 non-null   uint8
 53  CamperRV                      3466 non-null   uint8
 54  Condominium                   3466 non-null   uint8
 55  Cottage                       3466 non-null   uint8
 56  Farm stay                     3466 non-null   uint8
 57  Guest suite                   3466 non-null   uint8
 58  Guesthouse                    3466 non-null   uint8
 59  Hostel                        3466 non-null   uint8
 60  House                         3466 non-null   uint8
 61  Houseboat                     3466 non-null   uint8
 62  In-law                        3466 non-null   uint8
 63  Loft                          3466 non-null   uint8
 64  Other                         3466 non-null   uint8
 65  Resort                        3466 non-null   uint8
 66  Serviced apartment            3466 non-null   uint8
 67  Tent                          3466 non-null   uint8
 68  Tiny house                    3466 non-null   uint8
 69  Townhouse                     3466 non-null   uint8
 70  Villa                         3466 non-null   uint8
 71  Yurt                          3466 non-null   uint8
 72  Airbed                        3466 non-null   uint8
 73  Futon                         3466 non-null   uint8
 74  Pull-out Sofa                 3466 non-null   uint8
 75  Real Bed                      3466 non-null   uint8
 76  flexible                      3466 non-null   uint8
 77  moderate                      3466 non-null   uint8
 78  strict                        3466 non-null   uint8
 79  strict_14_with_grace_period   3466 non-null   uint8
 80  super_strict_30               3466 non-null   uint8
 81  super_strict_60               3466 non-null   uint8
dtypes: bool(3), float64(3), int64(9), object(10), uint8(57)
memory usage: 798.9+ KB

In [8]:
# Create Dummy Variables for Amenties variable
amen = dframe['amenities'].str.get_dummies(sep=',')
dum_df = pd.concat([dum_df,amen], axis=1)
dum_df.columns

Index(['X1', 'id', 'host_is_superhost', 'host_response_rate',
       'host_response_time', 'host_listings_count', 'host_identity_verified',
       'accommodates', 'neighbourhood_group_cleansed', 'property_type',
       ...
       'Wide clearance to bed', 'Wide clearance to shower', 'Wide doorway',
       'Wide entryway', 'Wide hallway clearance', 'Wifi', 'Window guards',
       'Wine cooler', 'translation missing: en.hosting_amenity_49',
       'translation missing: en.hosting_amenity_50'],
      dtype='object', length=259)

In [9]:
dum_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3466 entries, 0 to 3465
Columns: 259 entries, X1 to translation missing: en.hosting_amenity_50
dtypes: bool(3), float64(3), int64(186), object(10), uint8(57)
memory usage: 5.5+ MB

# Method # 2 Using Label Encoder for converting Categorical Labels into Dummy Variables

In [10]:
# First Make Copy of the Original Dataframe into a New Dataframe
# new_df = dframe.select_dtypes(include=['object']).copy() # Select only Object datatypes Columns
new_df = dframe.copy()
new_df

,X1,id,host_is_superhost,host_response_rate,host_response_time,host_listings_count,host_identity_verified,accommodates,neighbourhood_group_cleansed,property_type,...,bedrooms,beds,bed_type,amenities,cleaning_fee,minimum_nights,maximum_nights,instant_bookable,cancellation_policy,price
0,5460,22146017,False,99,within an hour,521,False,5,Downtown,Apartment,...,2,2,Real Bed,"TV,Internet,Wifi,Kitchen,Elevator,Heating,Fami...",129.00,2,1125,True,strict,279.00
1,4143,18638163,True,100,within an hour,1,True,2,Queen Anne,House,...,0,1,Real Bed,"TV,Cable TV,Internet,Wifi,Air conditioning,Kit...",50.00,2,30,True,moderate,99.00
2,5802,22734110,True,100,within an hour,1,False,4,Rainier Valley,Guest suite,...,1,2,Real Bed,"TV,Wifi,Air conditioning,Kitchen,Free street p...",25.00,2,28,False,moderate,75.00
3,776,3946674,True,90,within a few hours,1,True,2,Central Area,House,...,1,1,Real Bed,"Internet,Wifi,Kitchen,Pets live on this proper...",0.00,2,30,False,flexible,70.00
4,6064,23610186,True,100,within an hour,4,True,8,Beacon Hill,House,...,3,3,Real Bed,"TV,Wifi,Kitchen,Free parking on premises,Smoki...",99.00,2,12,False,flexible,242.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3461,5550,22208755,False,99,within an hour,521,False,5,Downtown,Apartment,...,2,2,Real Bed,"TV,Internet,Wifi,Air conditioning,Kitchen,Gym,...",129.00,2,1125,True,strict,350.00
3462,7391,28049926,False,100,within an hour,123,False,1,Capitol Hill,House,...,1,1,Real Bed,"Wifi,Kitchen,Heating,Essentials,Shampoo,Hanger...",15.00,1,21,True,strict_14_with_grace_period,30.00
3463,6056,23567364,True,100,within an hour,4,False,2,Other neighborhoods,House,...,1,1,Real Bed,"Wifi,Kitchen,Free parking on premises,Pets liv...",22.00,2,30,True,flexible,30.00
3464,1277,6728419,True,100,within a few hours,1,False,2,Other neighborhoods,Guest suite,...,1,1,Real Bed,"TV,Wifi,Free parking on premises,Indoor firepl...",25.00,1,1125,False,flexible,95.00
3465,6035,23483176,False,100,within an hour,2,False,2,Rainier Valley,Cottage,...,1,1,Real Bed,"Wifi,Kitchen,Free street parking,Heating,Smoke...",59.00,3,1125,False,moderate,100.00

In [11]:
# Using SciKit Learn
# Encoding make column using LabelEncoder
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
new_df['amenities_encoded'] = labelencoder.fit_transform(new_df['amenities'])
# Viewing few rows of make and its encoded columns
new_df[['amenities', 'amenities_encoded']].sample(20)

                                              amenities  amenities_encoded
2366  TV,Wifi,Kitchen,Free parking on premises,Indoo...               2159
3200  TV,Wifi,Kitchen,Free parking on premises,Gym,E...               2048
1841  TV,Wifi,Kitchen,Free street parking,Heating,Wa...               2315
2681  TV,Cable TV,Internet,Wifi,Kitchen,Free parking...                496
1971  Wifi,Air conditioning,Kitchen,Free street park...               2635
1808  TV,Wifi,Kitchen,Heating,Smoke detector,Carbon ...               2407
2889  TV,Internet,Wifi,Kitchen,Heating,Dryer,Essenti...               1353
1815  TV,Internet,Wifi,Air conditioning,Kitchen,Gym,...               1120
205   TV,Internet,Wifi,Kitchen,Free street parking,B...               1302
1077  TV,Cable TV,Wifi,Kitchen,Pets allowed,Free str...               1026
2507  TV,Internet,Wifi,Air conditioning,Kitchen,Free...               1090
2838  TV,Wifi,Air conditioning,Kitchen,Elevator,Indo...               1480
3432  Wifi,Kitchen,Free street parking,Heating,Famil...               2899
740   TV,Cable TV,Internet,Wifi,Kitchen,Paid parking...                586
1394  TV,Internet,Wifi,Free parking on premises,Brea...               1152
945   TV,Cable TV,Wifi,Free street parking,Washer,Dr...                794
620   TV,Wifi,Kitchen,Paid parking off premises,Free...               2462
979   TV,Internet,Wifi,Kitchen,Pets allowed,Heating,...               1387
2108  Wifi,Kitchen,Free parking on premises,Pets all...               2874
2584  Wifi,Kitchen,Free parking on premises,Heating,...               2823

In [12]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3466 entries, 0 to 3465
Data columns (total 26 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   X1                            3466 non-null   int64
 1   id                            3466 non-null   int64
 2   host_is_superhost             3466 non-null   bool
 3   host_response_rate            3466 non-null   object
 4   host_response_time            3466 non-null   object
 5   host_listings_count           3466 non-null   int64
 6   host_identity_verified        3466 non-null   bool
 7   accommodates                  3466 non-null   int64
 8   neighbourhood_group_cleansed  3466 non-null   object
 9   property_type                 3466 non-null   object
 10  room_type                     3466 non-null   object
 11  latitude                      3466 non-null   float64
 12  longitude                     3466 non-null   float64
 13  guests_included               3466 non-null   int64
 14  bathrooms                     3466 non-null   float64
 15  bedrooms                      3466 non-null   int64
 16  beds                          3466 non-null   int64
 17  bed_type                      3466 non-null   object
 18  amenities                     3466 non-null   object
 19  cleaning_fee                  3466 non-null   object
 20  minimum_nights                3466 non-null   int64
 21  maximum_nights                3466 non-null   int64
 22  instant_bookable              3466 non-null   bool
 23  cancellation_policy           3466 non-null   object
 24  price                         3466 non-null   object
 25  amenities_encoded             3466 non-null   int32
dtypes: bool(3), float64(3), int32(1), int64(9), object(10)
memory usage: 619.5+ KB

# Method # 3 Using Astype for converting Boolean into Interger Variables

In [13]:
new_df.host_is_superhost.value_counts()

False    1762
True     1704
Name: host_is_superhost, dtype: int64

In [14]:
# Convert a single column of boolean values to a column of integers 1 or 0
new_df['host_is_superhost'] = new_df['host_is_superhost'].astype('int32')
new_df.sample(10)

,X1,id,host_is_superhost,host_response_rate,host_response_time,host_listings_count,host_identity_verified,accommodates,neighbourhood_group_cleansed,property_type,...,beds,bed_type,amenities,cleaning_fee,minimum_nights,maximum_nights,instant_bookable,cancellation_policy,price,amenities_encoded
2253,6122,23724477,1,100,within an hour,42,True,4,Other neighborhoods,Guesthouse,...,1,Real Bed,"TV,Internet,Wifi,Kitchen,Free street parking,H...",84.00,2,180,False,strict_14_with_grace_period,77.00,1322
1460,3413,15898292,0,99,within an hour,1276,False,6,Downtown,Apartment,...,2,Real Bed,"TV,Cable TV,Internet,Wifi,Pool,Kitchen,Gym,Ele...",99.00,2,1125,True,strict_14_with_grace_period,999.00,643
2962,5367,21841224,0,100,within an hour,1,False,2,Ballard,Townhouse,...,1,Real Bed,"Wifi,Free parking on premises,Free street park...",15.00,1,1125,True,flexible,65.00,2664
2240,6545,24959196,1,100,within an hour,2,False,4,Cascade,Apartment,...,2,Real Bed,"TV,Wifi,Air conditioning,Kitchen,Pets allowed,...",90.00,2,10,False,moderate,135.00,1719
3461,5550,22208755,0,99,within an hour,521,False,5,Downtown,Apartment,...,2,Real Bed,"TV,Internet,Wifi,Air conditioning,Kitchen,Gym,...",129.00,2,1125,True,strict,350.00,1122
2776,4661,20189383,1,100,within an hour,1,False,4,Other neighborhoods,Guest suite,...,2,Real Bed,"TV,Wifi,Kitchen,Free parking on premises,Free ...",45.00,1,1124,True,flexible,125.00,1933
2889,2874,13790537,0,100,within an hour,2,False,2,Central Area,Apartment,...,1,Real Bed,"TV,Internet,Wifi,Kitchen,Heating,Dryer,Essenti...",0,2,7,False,flexible,75.00,1353
2062,7923,30010568,0,50,within a day,1,False,3,Lake City,Apartment,...,1,Real Bed,"TV,Wifi,Kitchen,Free parking on premises,Gym,H...",0,8,8,True,flexible,80.00,2050
2809,6167,23881540,0,100,within an hour,1,False,8,Ballard,Townhouse,...,5,Real Bed,"TV,Wifi,Kitchen,Free parking on premises,Free ...",150.00,2,1125,False,strict_14_with_grace_period,350.00,2023
3076,2191,11212116,0,99,within an hour,521,False,3,Downtown,Apartment,...,1,Real Bed,"TV,Internet,Wifi,Air conditioning,Kitchen,Gym,...",89.00,2,1125,True,strict,189.00,1118

In [15]:
# Convert a single column of boolean values to a column of integers 1 or 0
new_df['host_is_superhost'] = new_df['host_is_superhost'].astype('int32')
new_df['host_identity_verified'] = new_df['host_identity_verified'].astype('int32')
new_df['instant_bookable'] = new_df['instant_bookable'].astype('int32')

new_df.sample(10)

,X1,id,host_is_superhost,host_response_rate,host_response_time,host_listings_count,host_identity_verified,accommodates,neighbourhood_group_cleansed,property_type,...,beds,bed_type,amenities,cleaning_fee,minimum_nights,maximum_nights,instant_bookable,cancellation_policy,price,amenities_encoded
1103,1136,6115807,0,100,within a few hours,3,1,8,Queen Anne,House,...,4,Real Bed,"TV,Cable TV,Internet,Wifi,Kitchen,Free parking...",155.00,2,180,0,strict_14_with_grace_period,350.00,460
1715,7301,27705446,1,100,within an hour,2,0,2,Central Area,Apartment,...,1,Real Bed,"TV,Wifi,Kitchen,Free parking on premises,Free ...",20.00,2,30,1,flexible,55.00,1969
546,206,710370,1,100,within a few hours,7,1,6,Capitol Hill,Townhouse,...,3,Real Bed,"TV,Cable TV,Wifi,Kitchen,Free parking on premi...",175.00,3,365,0,strict_14_with_grace_period,199.00,833
19,5063,21188538,0,100,within an hour,1,0,4,Other neighborhoods,House,...,2,Real Bed,"TV,Wifi,Kitchen,Pets allowed,Free street parki...",55.00,2,1125,1,strict_14_with_grace_period,65.00,2521
2597,5372,21883153,1,100,within an hour,1,1,2,Delridge,Guest suite,...,1,Real Bed,"Wifi,Kitchen,Free parking on premises,Pets all...",40.00,2,15,1,moderate,45.00,2868
112,2167,11149363,1,100,within an hour,2,1,4,Other neighborhoods,Guest suite,...,2,Real Bed,"TV,Internet,Wifi,Air conditioning,Kitchen,Pets...",0,3,15,1,moderate,125.00,1145
1445,5195,21475211,1,100,within an hour,131,0,3,Cascade,Serviced apartment,...,1,Real Bed,"TV,Cable TV,Internet,Wifi,Kitchen,Paid parking...",75.00,2,1125,1,flexible,99.00,580
3006,6141,23781996,1,100,within an hour,2,0,2,West Seattle,Guest suite,...,2,Real Bed,"TV,Wifi,Free parking on premises,Heating,Smoke...",55.00,2,14,1,flexible,100.00,1781
2879,2005,9957555,1,100,within an hour,1,1,6,Central Area,House,...,4,Real Bed,"TV,Cable TV,Wifi,Kitchen,Free parking on premi...",125.00,3,1125,0,strict_14_with_grace_period,110.00,879
1758,1084,5785382,0,99,within an hour,1276,0,3,Downtown,Apartment,...,2,Real Bed,"TV,Cable TV,Internet,Wifi,Air conditioning,Kit...",99.00,2,1125,1,strict_14_with_grace_period,999.00,211

# Method # 4 Using Binary Encoder for converting Object Columns into Interger Variables

In [16]:
# importing the libraries
import category_encoders as cat_encoder
  
# creating a copy of the original data frame
df2 = dframe.select_dtypes(include=['object']).copy()

# Dropping irrelevant Columns "Price", "cleaning_fee"
df2.drop(["price", "cleaning_fee"], axis=1, inplace=True)
  
# creating an object BinaryEncoder
# this code calls all columns
# we can specify specific columns as well
encoder = cat_encoder.BinaryEncoder(cols = df2.columns)
  
# fitting the columns to a data frame
df_category_encoder = encoder.fit_transform( df2 )
  
display(df_category_encoder)

C:\Users\sanja\anaconda3\lib\site-packages\category_encoders\utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):

,host_response_rate_0,host_response_rate_1,host_response_rate_2,host_response_rate_3,host_response_rate_4,host_response_rate_5,host_response_time_0,host_response_time_1,host_response_time_2,neighbourhood_group_cleansed_0,...,amenities_7,amenities_8,amenities_9,amenities_10,amenities_11,amenities_12,cancellation_policy_0,cancellation_policy_1,cancellation_policy_2,cancellation_policy_3
0,0,0,0,0,0,1,0,0,1,0,...,0,0,0,0,0,1,0,0,0,1
1,0,0,0,0,1,0,0,0,1,0,...,0,0,0,0,1,0,0,0,1,0
2,0,0,0,0,1,0,0,0,1,0,...,0,0,0,0,1,1,0,0,1,0
3,0,0,0,0,1,1,0,1,0,0,...,0,0,0,1,0,0,0,0,1,1
4,0,0,0,0,1,0,0,0,1,0,...,0,0,0,1,0,1,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3461,0,0,0,0,0,1,0,0,1,0,...,1,1,1,0,0,1,0,0,0,1
3462,0,0,0,0,1,0,0,0,1,0,...,1,1,1,0,1,1,0,1,0,0
3463,0,0,0,0,1,0,0,0,1,0,...,1,1,1,0,1,1,0,0,1,1
3464,0,0,0,0,1,0,0,1,0,0,...,1,1,1,1,0,0,0,0,1,1
3465,0,0,0,0,1,0,0,0,1,0,...,1,1,1,1,0,1,0,0,1,0

# Further to be Explored:
# ===================
# import category_encoders as ce
#
# encoder = ce.BackwardDifferenceEncoder(cols=[...])
# encoder = ce.BaseNEncoder(cols=[...])
# encoder = ce.BinaryEncoder(cols=[...])
# encoder = ce.CatBoostEncoder(cols=[...])
# encoder = ce.CountEncoder(cols=[...])
# encoder = ce.GLMMEncoder(cols=[...])
# encoder = ce.HashingEncoder(cols=[...])
# encoder = ce.HelmertEncoder(cols=[...])
# encoder = ce.JamesSteinEncoder(cols=[...])
# encoder = ce.LeaveOneOutEncoder(cols=[...])
# encoder = ce.MEstimateEncoder(cols=[...])
# encoder = ce.OneHotEncoder(cols=[...])
# encoder = ce.OrdinalEncoder(cols=[...])
# encoder = ce.SumEncoder(cols=[...])
# encoder = ce.PolynomialEncoder(cols=[...])
# encoder = ce.TargetEncoder(cols=[...])
# encoder = ce.WOEEncoder(cols=[...])